# run tests then either validate version incremented on branches or create tag on main
name: build
run-name: building ${{ github.ref_name }}
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_BRANCH: origin/main
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with: 
          submodules: true
          fetch-depth: 0
      - name: run tests
        run: ./test/bats/bin/bats -r test/tests
      - name: validate version
        run: ./bin/validate_version.sh
      - name: tag version
        run: ./bin/tag.sh
