# Building in our case is basically just running tests
name: build
run-name: building ${{ github.ref_name }}
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with: 
          submodules: true
      - name: run tests
        run: /home/runner/work/PolyROM/PolyROM/test/bats/bin/bats -r /home/runner/work/PolyROM/PolyROM/test/tests
