# Validating branch correctness essentially is just making sure the version is incremented
name: validate branch
run-name: validating ${{ github.ref_name }}
on: 
  push:
    branches-ignore: [main]
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      BASE_BRANCH: origin/main
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: validate version
        run: ./bin/validate_version.sh
